apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.pythonapp.name }}
  namespace: default
  labels:
    app: {{ .Values.pythonapp.name }}
spec:
  replicas: {{ .Values.pythonapp.minReplicas }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Values.pythonapp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.pythonapp.name }}
    spec:
      containers:
      - name: {{ .Values.pythonapp.name }}
        image: {{ .Values.global.registry }}/pythonapp:pythonapp
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: {{ .Values.pythonapp.port }}
          name: {{ .Values.pythonapp.name }}
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 800m

---

kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.pythonapp.name }}-service
  namespace: default
spec:
  selector:
    app: {{ .Values.pythonapp.name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.pythonapp.port }}
      targetPort: {{ .Values.pythonapp.port }}

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: {{ .Values.pythonapp.name }}-service
          servicePort: {{ .Values.pythonapp.port }}
